### cadastrar folhas
POST https://localhost:5001/api/folha/create
Content-Type: application/json

{
    "HoraTrabalhada" : 200,
    "ValorHora" : 200,
    "Mes" : 12,
    "Ano" : 2021,
    "FuncionarioId" : "1"
}

### Listar folhas
GET https://localhost:5001/api/folha/list

### Buscar folha pelo id
GET https://localhost:5001/api/folha/getbyid/1

### Deletar produto
DELETE https://localhost:5001/api/folha/delete/1