### cadastrar funcionarios
POST https://localhost:5001/api/funcionario/create
Content-Type: application/json

{
    "Nome" : "Vitor",
    "Setor" : "Dev"
}

### Listar usuarios
GET https://localhost:5001/api/funcionario/list
